trigger: none

# Variable 'GIT_SSL_NO_VERIFY' was defined in the Variables tab
variables:
- name: GIT_SSL_NO_VERIFY
  value: 1

jobs:
- job: Job_1
  displayName: Python static code check
  timeoutInMinutes: 10
  cancelTimeoutInMinutes: 5
  pool:
    name: Testing
    demands:
    - Agent.Name -equals VV-Build

  steps:
  - checkout: self
    clean: true

  - template: templates\create_py_venv.yaml

  - template: templates\install_pip_packages.yaml
    parameters:
      venv_folder: $(Build.SourcesDirectory)\venv\
      project_folder: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Run pylint
    inputs:
      targetType: inline
      script: |
        Write-Output "Activate python virtual environment."
        $(Build.SourcesDirectory)\venv\Scripts\Activate.ps1

        Write-Output "Get changed files in this PR (compared to main branch):"
        $changedFiles = git diff --name-only --diff-filter=AM origin/main '*.py' | Select-String -NotMatch '__init__.py$'

        Write-Output "Changed python files are:" $changedFiles

        Write-Output "Run pylint on changed files."
        python $(Build.SourcesDirectory)\run_pylint.py $changedFiles

        Write-Output "Deactivate Python virtual environment."
        deactivate
