"""
File with logic to create parameterization Suite file using data from CSV and CAN EDS.
"""
import os
import sys
from utilities.parser.csv_parser import csv_parser
from utilities.parser.eds_parser import eds_parser


class parametrization_generator:
    """
    Class to implement logic to create parameterization suite file.
    """

    def __init__(self, pdo_prefix="Transmit", csv_file_path: str = None, eds_file_path: str = None) -> None:

        # Create a path for local template file.
        self.template_path = os.path.join(os.path.dirname(
            os.path.realpath(__file__)), "template.robot")

        print(f"CSV path:{csv_file_path}")
        # Instantiate CSV parser and parse CSV
        self.csv_data = csv_parser(file_path=csv_file_path)

        # Instantiate EDS parser and parse EDS for TPDO communication parameters (Max = XXXXh + 1FFh)
        self.tpdo_communication_parameters = eds_parser(
            file_path=eds_file_path, min_index=0x1800, max_index=0x19FF)

        # Instantiate EDS parser and parse EDS for TPDO communication mappings (Max = XXXXh + 1FFh)
        self.tpdo_mapping_parameters = eds_parser(
            file_path=eds_file_path, min_index=0x1A00, max_index=0x1BFF)

        # Instantiate EDS parser and parse EDS for RPDO communication parameters (Max = XXXXh + 1FFh)
        self.rpdo_communication_parameters = eds_parser(
            file_path=eds_file_path, min_index=0x1400, max_index=0x15FF)

        # Instantiate EDS parser and parse EDS for RPDO communication mappings (Max = XXXXh + 1FFh)
        self.rpdo_mapping_parameters = eds_parser(
            file_path=eds_file_path, min_index=0x1600, max_index=0x17FF)

        # Instantiate EDS parser and parse all from EDS (0x1000 -> 0xFFFF)
        self.all_eds_parameters = eds_parser(
            file_path=eds_file_path, min_index=0x1000, max_index=0xFFFF)

        self.pdo_prefix = pdo_prefix

    def create_parametrization_suite(self, robot_file_path: str = None):
        """
        Creates Robot parameterization suite to user defined location.

        *Arguments:*

        robot_file_path (str): Path to robot file which will be generated.
        """
        if robot_file_path is None:
            raise ValueError("No robot file path defined.")

        generated_content = self._generate_robot_tests()

        # Read Robot template file
        with open(self.template_path, "r", encoding='UTF-8') as template_file:
            content = template_file.read()

        # Update description to generated file.
        updated_content = content.replace(
            "DESCRIPTION_BY_GENERATOR", "DO NOT MODIFY THIS CONTENT, THIS IS AUTOGENERATED FROM CSV.")

        # Update PDO refix to generated file.
        updated_content = updated_content.replace(
            "PDO_PREFIX_BY_GENERATOR", self.pdo_prefix)

        # Update content with generated data
        updated_content = updated_content.replace(
            'KEYWORD_CALLS_BY_GENERATOR', generated_content)

        # Save new robot file with updated content
        with open(robot_file_path, "w", encoding='UTF-8') as generated_file:
            generated_file.write(updated_content)

    def _parse_id_before_colon(self, input_string):
        """
        Parses id from string before colon ':'.

        *Arguments:*

        input_string: string to be parsed, assumed to be in format 123:ACB

        *Returns:*

        (str): parsed text.
        """
        # Find the position of the colon
        colon_pos = input_string.find(':')

        # If colon is found, slice the string up to that position
        if colon_pos != -1:
            parsed_text = input_string[:colon_pos]
            return parsed_text
        else:
            raise ValueError("No colon ':' defined in CSV subindex map.")

    def _parse_text_after_colon(self, input_string):
        """
        Parses text from string after colon ':'.

        *Arguments:*

        input_string: string to be parsed, assumed to be in format 123:ACB

        *Returns:*

        (str): parsed text.
        """
        # Find the position of the colon
        colon_pos = input_string.find(':')

        # If colon is found, slice the string after that position
        if colon_pos != -1:
            parsed_text = input_string[colon_pos + 1:].strip()
            return parsed_text
        else:
            raise ValueError("No colon ':' defined in CSV subindex map.")

    def create_pdo_mapping_values(self, pdo_item):
        """
        Generates pdo mapping values.

        *Arguments:*

        pdo_item: instance of CSV item class

        *Returns:*

        (str): 0x<index><sub-index><length>   0x<index><sub-index><length>   0x<index><sub-index><length>
        """
        ret_val = ""
        for item in pdo_item.data:
            # Get id from CSV cell text
            item_id = self._parse_id_before_colon(item)
            # Get parameter name from CSV cell text
            item_text = self._parse_text_after_colon(item)
            # Create 0x<index><sub-index><length> values separated by two spaces
            pdo_map_val = self.all_eds_parameters.create_pdo_mapping_value(
                item_id, item_text)
            ret_val += pdo_map_val
        return ret_val[:-2]

    def _generate_robot_tests(self):
        """
        Generates content for robot template file.

        *Returns:*

        (str): Test case format utilizing test template
        """
        content = ""
        for index, item in enumerate(self.csv_data.items):
            if "Transmit" in self.pdo_prefix:
                com_parameter_name = list(self.tpdo_communication_parameters.indexes.values())[
                    int(item.pdo_index)-1].parameter_name
                mapping_parameter_name = list(self.tpdo_mapping_parameters.indexes.values())[
                    int(item.pdo_index)-1].parameter_name
            else:
                com_parameter_name = list(self.rpdo_communication_parameters.indexes.values())[
                    int(item.pdo_index)-1].parameter_name
                mapping_parameter_name = list(self.rpdo_mapping_parameters.indexes.values())[
                    int(item.pdo_index)-1].parameter_name
            if 0 < len(self.create_pdo_mapping_values(pdo_item=self.csv_data.items[index])):
                content += f"\n\t# Configure PDO {item.pdo_index} ({item.pdo_hex}/{item.pdo_dec})\n"
                content += f"\tConfigure PDO  {self.create_pdo_mapping_values(pdo_item=self.csv_data.items[index])}\n"
            else:
                content += f"\n\t# Disable PDO {item.pdo_index} ({item.pdo_hex}/{item.pdo_dec})\n"
                content += "\tConfigure PDO\n"
            content += "\t...  node_id=${FW_NODE_ID}\n"
            content += f"\t...  cob_id_decimal={self.csv_data.items[index].pdo_dec}\n"
            content += f"\t...  pdo_com_parameter_name={com_parameter_name}\n"
            content += f"\t...  pdo_mapping_parameter_name={mapping_parameter_name}\n"
            content += f"\t...  transmission_type={self.csv_data.items[index].transmission_type}\n"
            content += f"\t...  inhibit_time={self.csv_data.items[index].inhibit_time}\n"
            content += f"\t...  event_timer={self.csv_data.items[index].event_timer}\n"
            content += f"\t...  sync_start_value={self.csv_data.items[index].sync_start_value}\n"

            content = content.replace("\t", "    ")
        return content.strip()


if __name__ == "__main__":
    # Check arguments
    if len(sys.argv) < 5:
        print("****\nNot enough arguments\nUse: python .\\python_libs\\utilities\\parametrization_generator\\parametrization_generator.py "
              "Transmit ate-fw-eds.eds TPDO SL8X1_01_Epec_C02.eds tpdo_mapping.csv dut_tpdo_configuration.resource\n****")
        sys.exit(1)

    # Ignore first argument, the file itself
    args = sys.argv[1:]
    print(args)

    generator = parametrization_generator(
        pdo_prefix=args[0], csv_file_path=args[2], eds_file_path=args[1])
    generator.create_parametrization_suite(
        robot_file_path=args[3])
