[tool.robocop.lint]
reports = ["all"]
configure = [
    "line-too-long.line_length=150",
    "too-long-test-case.max_len=100",
    "too-many-test-cases.max_testcases=125",
    "too-many-calls-in-test-case.max_calls=30",
    "too-many-calls-in-keyword.max_calls=50",
    "too-long-keyword.max_len=100",
    "too-many-arguments.max_args=10",
    "file-too-long.max_lines=1500"
]